################################################################################
# SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
################################################################################

infer_config {
  unique_id: 1
  gpu_ids: [0]
  max_batch_size: 4 
  backend {
    inputs: [ {
      name: "Input"
    }]
    outputs: [
      {name: "generate_detections"},
      {name: "mask_fcn_logits/BiasAdd"}
    ]
    triton {
      model_name: "peopleSegNet"
      version: -1
      grpc {
        url: "localhost:10001"
      }
    }
  }

  preprocess {
    network_format: MEDIA_FORMAT_NONE
    tensor_order: TENSOR_ORDER_LINEAR
    tensor_name: "Input"
    maintain_aspect_ratio: 0
    frame_scaling_hw: FRAME_SCALING_HW_DEFAULT
    frame_scaling_filter: 1
    normalize {
      scale_factor: 0.017507
      channel_offsets: [123.675, 116.280, 103.53]
    }
  }

  postprocess {
    labelfile_path: "../../../configs/nvinfer/peopleSegNet_tao/peopleSegNet_labels.txt"
    detection {
      num_detected_classes: 2
      custom_parse_bbox_func: "NvDsInferParseCustomMrcnnTLTV2"
    }
  }

  custom_lib {
    path: "../../../post_processor/libnvds_infercustomparser_tao.so"
  }

  extra {
    copy_input_to_host_buffers: false
    output_buffer_pool_size: 2
  }
}
input_control {
  process_mode: PROCESS_MODE_FULL_FRAME
  operate_on_gie_id: -1
  interval: 0
}
